using NetworkGenerator.Generators;
using NetworkGenerator.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace NetworkGenerator.FileUtilities
{
	public static class Generator
	{
		private static string GenerateXmlData(List<NetworkNode> nodes)
		{
			var xmlText = "";

			xmlText += "<PACKETTRACER5>";
			xmlText += "<VERSION>4.2</VERSION>";
			xmlText += "<NETWORK>";

			xmlText += "<DEVICES>";
			foreach (NetworkNode node in nodes)
            {
				// ROUTER
				xmlText += "<DEVICE>";
				xmlText += "<ENGINE>";
				xmlText += "<TYPE model='1841' >Router</TYPE>";
				xmlText += "<NAME translate='true' >" + node.Router.Name + "</NAME>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<DESCRIPTION></DESCRIPTION>";
				xmlText += "<MODULE>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODEL/>";
				xmlText += "<SLOT>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODULE>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODEL/>";
				xmlText += "<SLOT>";
				xmlText += "<TYPE>eInterfaceCard</TYPE>";
				xmlText += "</SLOT>";
				xmlText += "<SLOT>";
				xmlText += "<TYPE>eInterfaceCard</TYPE>";
				xmlText += "</SLOT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>false</POWER>";
				xmlText += "<PINS>false</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Router.Port1MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Router.Port1MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "<IP/>";
				xmlText += "<SUBNET/>";
				xmlText += "<TIMEOUT>14400000</TIMEOUT>";
				xmlText += "<IPV6_ENABLED>false</IPV6_ENABLED>";
				xmlText += "<IPV6_ADDRESS_AUTOCONFIG>false</IPV6_ADDRESS_AUTOCONFIG>";
				xmlText += "<IPV6_LINK_LOCAL/>";
				xmlText += "<IPV6_DEFAULT_LINK_LOCAL>" + node.Router.Port1IpV6DefaultLink + "</IPV6_DEFAULT_LINK_LOCAL>";
				xmlText += "<IPV6_ADDRESSES/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>false</POWER>";
				xmlText += "<PINS>false</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Router.Port2MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Router.Port2MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "<IP/>";
				xmlText += "<SUBNET/>";
				xmlText += "<TIMEOUT>14400000</TIMEOUT>";
				xmlText += "<IPV6_ENABLED>false</IPV6_ENABLED>";
				xmlText += "<IPV6_ADDRESS_AUTOCONFIG>false</IPV6_ADDRESS_AUTOCONFIG>";
				xmlText += "<IPV6_LINK_LOCAL/>";
				xmlText += "<IPV6_DEFAULT_LINK_LOCAL>" + node.Router.Port2IpV6DefaultLink + "</IPV6_DEFAULT_LINK_LOCAL>";
				xmlText += "<IPV6_ADDRESSES/>";
				xmlText += "</PORT>";
				xmlText += "</MODULE>";
				xmlText += "</SLOT>";
				xmlText += "</MODULE>";
				xmlText += "<RUNNINGCONFIG>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>version 12.4</LINE>";
				xmlText += "<LINE>no service password-encryption</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>hostname Router</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>ip ssh version 1</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/0</LINE>";
				xmlText += "<LINE> no ip address</LINE>";
				xmlText += "<LINE> duplex auto</LINE>";
				xmlText += "<LINE> speed auto</LINE>";
				xmlText += "<LINE> shutdown</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/1</LINE>";
				xmlText += "<LINE> no ip address</LINE>";
				xmlText += "<LINE> duplex auto</LINE>";
				xmlText += "<LINE> speed auto</LINE>";
				xmlText += "<LINE> shutdown</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface Vlan1</LINE>";
				xmlText += "<LINE> no ip address</LINE>";
				xmlText += "<LINE> shutdown</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>ip classless</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>no cdp run</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>line con 0</LINE>";
				xmlText += "<LINE>line vty 0 4</LINE>";
				xmlText += "<LINE> login</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>end</LINE>";
				xmlText += "</RUNNINGCONFIG>";
				xmlText += "<STARTUPCONFIG/>";
				xmlText += "<CURRENT_COMMAND_SET>1841_advip_12.4</CURRENT_COMMAND_SET>";
				xmlText += "<FILE_MANAGER>";
				xmlText += "<FILE class='CDirectory' >";
				xmlText += "<FILE_NUMBER>0</FILE_NUMBER>";
				xmlText += "<NAME></NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT/>";
				xmlText += "<FILES>";
				xmlText += "<FILE class='CFileSystem' >";
				xmlText += "<FILE_NUMBER>0</FILE_NUMBER>";
				xmlText += "<NAME>flash:</NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT/>";
				xmlText += "<FILES>";
				xmlText += "<FILE class='CFile' >";
				xmlText += "<FILE_NUMBER>1</FILE_NUMBER>";
				xmlText += "<NAME>c1841-advipservicesk9-mz.124-15.T1.bin</NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT class='CIosFileContent' >";
				xmlText += "<DEVICE_TYPE>Router</DEVICE_TYPE>";
				xmlText += "<SET_NAME>1841_advip_12.4</SET_NAME>";
				xmlText += "</FILE_CONTENT>";
				xmlText += "</FILE>";
				xmlText += "</FILES>";
				xmlText += "<FILE_COUNTER>1</FILE_COUNTER>";
				xmlText += "<CAPACITY>64016384</CAPACITY>";
				xmlText += "</FILE>";
				xmlText += "</FILES>";
				xmlText += "</FILE>";
				xmlText += "</FILE_MANAGER>";
				xmlText += "<BOOT_SYSTEMS/>";
				xmlText += "<CONFIG_REGISTER>8450</CONFIG_REGISTER>";
				xmlText += "<NEXT_CONFIG_REGISTER>8450</NEXT_CONFIG_REGISTER>";
				xmlText += "<BUILD_IN_ADDR>" + node.Router.BuildInAddr + "</BUILD_IN_ADDR>";
				xmlText += "<SECURITY>";
				xmlText += "<KEY_NAME></KEY_NAME>";
				xmlText += "<TEMP_KEY_NAME></TEMP_KEY_NAME>";
				xmlText += "<RSA_KEY></RSA_KEY>";
				xmlText += "<TEMP_RSA_KEY></TEMP_RSA_KEY>";
				xmlText += "<TIME_DATE></TIME_DATE>";
				xmlText += "<ENABLED>0</ENABLED>";
				xmlText += "</SECURITY>";
				xmlText += "<VLANS>";
				xmlText += "<VLAN number='1' name='default' />";
				xmlText += "<VLAN number='1002' name='fddi-default' />";
				xmlText += "<VLAN number='1003' name='token-ring-default' />";
				xmlText += "<VLAN number='1004' name='fddinet-default' />";
				xmlText += "<VLAN number='1005' name='trnet-default' />";
				xmlText += "</VLANS>";
				xmlText += "<VTP>";
				xmlText += "<DOMAIN_NAME></DOMAIN_NAME>";
				xmlText += "<MODE>0</MODE>";
				xmlText += "<VERSION>1</VERSION>";
				xmlText += "<PASSWORD></PASSWORD>";
				xmlText += "<CONFIG_REVISION>0</CONFIG_REVISION>";
				xmlText += "<UPDATER_IP>0.0.0.0</UPDATER_IP>";
				xmlText += "<UPDATE_TIMESTAMP>0-0-00 00:00:00</UPDATE_TIMESTAMP>";
				xmlText += "</VTP>";
				xmlText += "</ENGINE>";
				xmlText += "<WORKSPACE>";
				xmlText += "<LOGICAL>";
				xmlText += "<X>" + node.Router.XCoordinate + "</X>";
				xmlText += "<Y>" + node.Router.YCoordinate + "</Y>";
				xmlText += "<DEVCLUSTERID>1-1</DEVCLUSTERID>";
				xmlText += "</LOGICAL>";
				xmlText += "<PHYSICAL translate='true' >Intercity,Home City,Corporate Office,Main Wiring Closet,Rack," + node.Router.Name + "</PHYSICAL>";
				xmlText += "</WORKSPACE>";
				xmlText += "</DEVICE>";

				// SWITCH 1
				xmlText += "<DEVICE>";
				xmlText += "<ENGINE>";
				xmlText += "<TYPE model='2950-24' >Switch</TYPE>";
				xmlText += "<NAME translate='true' >" + node.Switch1.Name + "</NAME>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<DESCRIPTION></DESCRIPTION>";
				xmlText += "<MODULE>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODEL/>";
				xmlText += "<SLOT>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODULE>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODEL/>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port1MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port1MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port2MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port2MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port3MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port3MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port4MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port4MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port5MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port5MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port6MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port6MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port7MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port7MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port8MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port8MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port9MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port9MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port10MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port10MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port11MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port11MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port12MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port12MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port13MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port13MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port14MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port14MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port15MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port15MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port16MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port16MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port17MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port17MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port18MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port18MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port19MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port19MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port20MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port20MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port21MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port21MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port22MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port22MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port23MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port23MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch1.Port24MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch1.Port24MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "</MODULE>";
				xmlText += "</SLOT>";
				xmlText += "</MODULE>";
				xmlText += "<RUNNINGCONFIG>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>version 12.1</LINE>";
				xmlText += "<LINE>no service password-encryption</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>hostname Switch</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/1</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/2</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/3</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/4</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/5</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/6</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/7</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/8</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/9</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/10</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/11</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/12</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/13</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/14</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/15</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/16</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/17</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/18</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/19</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/20</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/21</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/22</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/23</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/24</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface Vlan1</LINE>";
				xmlText += "<LINE> no ip address</LINE>";
				xmlText += "<LINE> shutdown</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>line con 0</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>line vty 0 4</LINE>";
				xmlText += "<LINE> login</LINE>";
				xmlText += "<LINE>line vty 5 15</LINE>";
				xmlText += "<LINE> login</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>end</LINE>";
				xmlText += "</RUNNINGCONFIG>";
				xmlText += "<STARTUPCONFIG/>";
				xmlText += "<CURRENT_COMMAND_SET>2950_12.1_EA4</CURRENT_COMMAND_SET>";
				xmlText += "<FILE_MANAGER>";
				xmlText += "<FILE class='CDirectory' >";
				xmlText += "<FILE_NUMBER>0</FILE_NUMBER>";
				xmlText += "<NAME></NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT/>";
				xmlText += "<FILES>";
				xmlText += "<FILE class='CFileSystem' >";
				xmlText += "<FILE_NUMBER>0</FILE_NUMBER>";
				xmlText += "<NAME>flash:</NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT/>";
				xmlText += "<FILES>";
				xmlText += "<FILE class='CFile' >";
				xmlText += "<FILE_NUMBER>1</FILE_NUMBER>";
				xmlText += "<NAME>c2950-i6q4l2-mz.121-22.EA4.bin</NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT class='CIosFileContent' >";
				xmlText += "<DEVICE_TYPE>Switch</DEVICE_TYPE>";
				xmlText += "<SET_NAME>2950_12.1_EA4</SET_NAME>";
				xmlText += "</FILE_CONTENT>";
				xmlText += "</FILE>";
				xmlText += "</FILES>";
				xmlText += "<FILE_COUNTER>1</FILE_COUNTER>";
				xmlText += "<CAPACITY>64016384</CAPACITY>";
				xmlText += "</FILE>";
				xmlText += "</FILES>";
				xmlText += "</FILE>";
				xmlText += "</FILE_MANAGER>";
				xmlText += "<BOOT_SYSTEMS/>";
				xmlText += "<CONFIG_REGISTER>15</CONFIG_REGISTER>";
				xmlText += "<NEXT_CONFIG_REGISTER>15</NEXT_CONFIG_REGISTER>";
				xmlText += "<BUILD_IN_ADDR>" + node.Switch1.BuildInAddr + "</BUILD_IN_ADDR>";
				xmlText += "<VLANS>";
				xmlText += "<VLAN number='1' name='default' />";
				xmlText += "<VLAN number='1002' name='fddi-default' />";
				xmlText += "<VLAN number='1003' name='token-ring-default' />";
				xmlText += "<VLAN number='1004' name='fddinet-default' />";
				xmlText += "<VLAN number='1005' name='trnet-default' />";
				xmlText += "</VLANS>";
				xmlText += "<VTP>";
				xmlText += "<DOMAIN_NAME></DOMAIN_NAME>";
				xmlText += "<MODE>0</MODE>";
				xmlText += "<VERSION>1</VERSION>";
				xmlText += "<PASSWORD></PASSWORD>";
				xmlText += "<CONFIG_REVISION>0</CONFIG_REVISION>";
				xmlText += "<UPDATER_IP>0.0.0.0</UPDATER_IP>";
				xmlText += "<UPDATE_TIMESTAMP>0-0-00 00:00:00</UPDATE_TIMESTAMP>";
				xmlText += "</VTP>";
				xmlText += "</ENGINE>";
				xmlText += "<WORKSPACE>";
				xmlText += "<LOGICAL>";
				xmlText += "<X>" + node.Switch1.XCoordinate + "</X>";
				xmlText += "<Y>" + node.Switch1.YCoordinate + "</Y>";
				xmlText += "<DEVCLUSTERID>1-1</DEVCLUSTERID>";
				xmlText += "</LOGICAL>";
				xmlText += "<PHYSICAL translate='true' >Intercity,Home City,Corporate Office,Main Wiring Closet,Rack," + node.Switch1.Name + "</PHYSICAL>";
				xmlText += "</WORKSPACE>";
				xmlText += "</DEVICE>";

				// SWITCH 2
				xmlText += "<DEVICE>";
				xmlText += "<ENGINE>";
				xmlText += "<TYPE model='2950-24' >Switch</TYPE>";
				xmlText += "<NAME translate='true' >" + node.Switch2.Name + "</NAME>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<DESCRIPTION></DESCRIPTION>";
				xmlText += "<MODULE>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODEL/>";
				xmlText += "<SLOT>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODULE>";
				xmlText += "<TYPE>eNonRemovableModule</TYPE>";
				xmlText += "<MODEL/>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port1MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port1MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port2MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port2MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port3MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port3MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port4MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port4MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port5MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port5MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port6MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port6MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port7MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port7MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port8MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port8MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port9MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port9MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port10MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port10MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port11MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port11MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port12MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port12MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port13MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port13MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port14MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port14MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port15MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port15MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port16MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port16MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port17MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port17MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port18MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port18MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port19MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port19MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port20MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port20MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port21MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port21MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port22MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port22MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port23MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port23MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "<PORT>";
				xmlText += "<TYPE>eCopperFastEthernet</TYPE>";
				xmlText += "<POWER>true</POWER>";
				xmlText += "<PINS>true</PINS>";
				xmlText += "<BANDWIDTH>100000</BANDWIDTH>";
				xmlText += "<FULLDUPLEX>false</FULLDUPLEX>";
				xmlText += "<AUTONEGOTIATEBANDWIDTH>true</AUTONEGOTIATEBANDWIDTH>";
				xmlText += "<AUTONEGOTIATEDUPLEX>true</AUTONEGOTIATEDUPLEX>";
				xmlText += "<MACADDRESS>" + node.Switch2.Port24MacAddress + "</MACADDRESS>";
				xmlText += "<BIA>" + node.Switch2.Port24MacAddress + "</BIA>";
				xmlText += "<CLOCKRATE>0</CLOCKRATE>";
				xmlText += "<DESCRIPTION/>";
				xmlText += "</PORT>";
				xmlText += "</MODULE>";
				xmlText += "</SLOT>";
				xmlText += "</MODULE>";
				xmlText += "<RUNNINGCONFIG>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>version 12.1</LINE>";
				xmlText += "<LINE>no service password-encryption</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>hostname Switch</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/1</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/2</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/3</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/4</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/5</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/6</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/7</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/8</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/9</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/10</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/11</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/12</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/13</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/14</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/15</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/16</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/17</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/18</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/19</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/20</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/21</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/22</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/23</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface FastEthernet0/24</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>interface Vlan1</LINE>";
				xmlText += "<LINE> no ip address</LINE>";
				xmlText += "<LINE> shutdown</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>line con 0</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>line vty 0 4</LINE>";
				xmlText += "<LINE> login</LINE>";
				xmlText += "<LINE>line vty 5 15</LINE>";
				xmlText += "<LINE> login</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>!</LINE>";
				xmlText += "<LINE>end</LINE>";
				xmlText += "</RUNNINGCONFIG>";
				xmlText += "<STARTUPCONFIG/>";
				xmlText += "<CURRENT_COMMAND_SET>2950_12.1_EA4</CURRENT_COMMAND_SET>";
				xmlText += "<FILE_MANAGER>";
				xmlText += "<FILE class='CDirectory' >";
				xmlText += "<FILE_NUMBER>0</FILE_NUMBER>";
				xmlText += "<NAME></NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT/>";
				xmlText += "<FILES>";
				xmlText += "<FILE class='CFileSystem' >";
				xmlText += "<FILE_NUMBER>0</FILE_NUMBER>";
				xmlText += "<NAME>flash:</NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT/>";
				xmlText += "<FILES>";
				xmlText += "<FILE class='CFile' >";
				xmlText += "<FILE_NUMBER>1</FILE_NUMBER>";
				xmlText += "<NAME>c2950-i6q4l2-mz.121-22.EA4.bin</NAME>";
				xmlText += "<DATE_TIME>0</DATE_TIME>";
				xmlText += "<PERMISSION>6</PERMISSION>";
				xmlText += "<FILE_CONTENT class='CIosFileContent' >";
				xmlText += "<DEVICE_TYPE>Switch</DEVICE_TYPE>";
				xmlText += "<SET_NAME>2950_12.1_EA4</SET_NAME>";
				xmlText += "</FILE_CONTENT>";
				xmlText += "</FILE>";
				xmlText += "</FILES>";
				xmlText += "<FILE_COUNTER>1</FILE_COUNTER>";
				xmlText += "<CAPACITY>64016384</CAPACITY>";
				xmlText += "</FILE>";
				xmlText += "</FILES>";
				xmlText += "</FILE>";
				xmlText += "</FILE_MANAGER>";
				xmlText += "<BOOT_SYSTEMS/>";
				xmlText += "<CONFIG_REGISTER>15</CONFIG_REGISTER>";
				xmlText += "<NEXT_CONFIG_REGISTER>15</NEXT_CONFIG_REGISTER>";
				xmlText += "<BUILD_IN_ADDR>" + node.Switch2.BuildInAddr + "</BUILD_IN_ADDR>";
				xmlText += "<VLANS>";
				xmlText += "<VLAN number='1' name='default' />";
				xmlText += "<VLAN number='1002' name='fddi-default' />";
				xmlText += "<VLAN number='1003' name='token-ring-default' />";
				xmlText += "<VLAN number='1004' name='fddinet-default' />";
				xmlText += "<VLAN number='1005' name='trnet-default' />";
				xmlText += "</VLANS>";
				xmlText += "<VTP>";
				xmlText += "<DOMAIN_NAME></DOMAIN_NAME>";
				xmlText += "<MODE>0</MODE>";
				xmlText += "<VERSION>1</VERSION>";
				xmlText += "<PASSWORD></PASSWORD>";
				xmlText += "<CONFIG_REVISION>0</CONFIG_REVISION>";
				xmlText += "<UPDATER_IP>0.0.0.0</UPDATER_IP>";
				xmlText += "<UPDATE_TIMESTAMP>0-0-00 00:00:00</UPDATE_TIMESTAMP>";
				xmlText += "</VTP>";
				xmlText += "</ENGINE>";
				xmlText += "<WORKSPACE>";
				xmlText += "<LOGICAL>";
				xmlText += "<X>" + node.Switch2.XCoordinate + "</X>";
				xmlText += "<Y>" + node.Switch2.YCoordinate + "</Y>";
				xmlText += "<DEVCLUSTERID>1-1</DEVCLUSTERID>";
				xmlText += "</LOGICAL>";
				xmlText += "<PHYSICAL translate='true' >Intercity,Home City,Corporate Office,Main Wiring Closet,Rack," + node.Switch2.Name + "</PHYSICAL>";
				xmlText += "</WORKSPACE>";
				xmlText += "</DEVICE>";
			}
			xmlText += "</DEVICES>";

			xmlText += "<LINKS>";

			foreach (NetworkNode node in nodes)
			{
				// ROUTER TO SWITCH1
				xmlText += "<LINK>";
				xmlText += "<TYPE>eCopper</TYPE>";
				xmlText += "<CABLE>";
				xmlText += "<LENGTH>0</LENGTH>";
				xmlText += "<FROM>" + node.Router.Id + "</FROM>";
				xmlText += "<PORT>FastEthernet0/0</PORT>";
				xmlText += "<TO>" + node.Switch1.Id + "</TO>";
				xmlText += "<PORT>FastEthernet0/1</PORT>";
				xmlText += "<TYPE>eStraightThrough</TYPE>";
				xmlText += "</CABLE>";
				xmlText += "</LINK>";

				// ROUTER TO SWITCH2
				xmlText += "<LINK>";
				xmlText += "<TYPE>eCopper</TYPE>";
				xmlText += "<CABLE>";
				xmlText += "<LENGTH>0</LENGTH>";
				xmlText += "<FROM>" + node.Router.Id + "</FROM>";
				xmlText += "<PORT>FastEthernet0/1</PORT>";
				xmlText += "<TO>" + node.Switch2.Id + "</TO>";
				xmlText += "<PORT>FastEthernet0/1</PORT>";
				xmlText += "<TYPE>eStraightThrough</TYPE>";
				xmlText += "</CABLE>";
				xmlText += "</LINK>";
			}

			for(int i=0; i<nodes.Count; i++)
            {
				for(int j=(i+1); j<nodes.Count; j++)
                {
					Tuple<string, string> availablePortRouter1 = nodes[i].GetAvailablePort();
					Tuple<string, string> availablePortRouter2 = nodes[j].GetAvailablePort();

					xmlText += "<LINK>";
					xmlText += "<TYPE>eCopper</TYPE>";
					xmlText += "<CABLE>";
					xmlText += "<LENGTH>0</LENGTH>";
					xmlText += "<FROM>" + availablePortRouter1.Item1 + "</FROM>";
					xmlText += "<PORT>" + availablePortRouter1.Item2 + "</PORT>";
					xmlText += "<TO>" + availablePortRouter2.Item1 + "</TO>";
					xmlText += "<PORT>" + availablePortRouter2.Item2 + "</PORT>";
					xmlText += "<TYPE>eCrossOver</TYPE>";
					xmlText += "</CABLE>";
					xmlText += "</LINK>";
				}
			}
			xmlText += "</LINKS>";

			xmlText += "<DESCRIPTION translate='true' ></DESCRIPTION>";
			xmlText += "</NETWORK>";
			xmlText += "<SCENARIOSET>";
			xmlText += "<SCENARIO>";
			xmlText += "<NAME translate='true' >Scenario 0</NAME>";
			xmlText += "<DESCRIPTION translate='true' />";
			xmlText += "</SCENARIO>";
			xmlText += "</SCENARIOSET>";
			xmlText += "<OPTIONS>";
			xmlText += "<LANGUAGE>default.ptl</LANGUAGE>";
			xmlText += "<ANIMATION>true</ANIMATION>";
			xmlText += "<SOUND>true</SOUND>";
			xmlText += "<DOCK>true</DOCK>";
			xmlText += "<LOGGING>true</LOGGING>";
			xmlText += "<PASS/>";
			xmlText += "<CONFIGPATH>./</CONFIGPATH>";
			xmlText += "<MODELSHOWN>false</MODELSHOWN>";
			xmlText += "<LINKLIGHTSSHOWN>true</LINKLIGHTSSHOWN>";
			xmlText += "<PORTSHOWN>false</PORTSHOWN>";
			xmlText += "<BACKGROUNDS>";
			xmlText += "<IMAGE second='../backgrounds/logical/grid_10x10.png' first='Logical' />";
			xmlText += "<IMAGE second='../backgrounds/logical/grid_25x25.png' first='Logical' />";
			xmlText += "<IMAGE second='../backgrounds/logical/grid_50x50.png' first='Logical' />";
			xmlText += "<IMAGE second='../backgrounds/logical/grid_100x100.png' first='Logical' />";
			xmlText += "<IMAGE second='../backgrounds/intercity/gGeoViewInterCity.png' first='Intercity' />";
			xmlText += "<IMAGE second='../backgrounds/city/gGeoViewCity.png' first='City' />";
			xmlText += "<IMAGE second='../backgrounds/city/gCiscoCampus.jpg' first='City' />";
			xmlText += "<IMAGE second='../backgrounds/building/gGeoViewBuilding.png' first='Building' />";
			xmlText += "</BACKGROUNDS>";
			xmlText += "<HIDEPHYSICAL>false</HIDEPHYSICAL>";
			xmlText += "<HIDECONFIG>false</HIDECONFIG>";
			xmlText += "<HIDECLI>false</HIDECLI>";
			xmlText += "<HIDEDESKTOP>false</HIDEDESKTOP>";
			xmlText += "<HIDEGUI>false</HIDEGUI>";
			xmlText += "<HIDEDEVICELABEL>false</HIDEDEVICELABEL>";
			xmlText += "<ACCESSIBLE>false</ACCESSIBLE>";
			xmlText += "<FONT>";
			xmlText += "<CLIFONT family='Courier New' pointsize='8 ' />";
			xmlText += "<HEADERFONT family='Verdana' pointsize='8 ' />";
			xmlText += "<WORKSPACEFONT family='Verdana' pointsize='8 ' />";
			xmlText += "<ACTIVITYFONT family='Verdana' pointsize='8 ' />";
			xmlText += "<FILEMENUFONT family='Tahoma' pointsize='8 ' />";
			xmlText += "<TABSWITCH family='Verdana' pointsize='10 ' />";
			xmlText += "<TOOLTIP family='Courier New' pointsize='8 ' />";
			xmlText += "<BUTTONLABELS family='Verdana' pointsize='8 ' />";
			xmlText += "</FONT>";
			xmlText += "<BUFFER_FULL_ACTION>0</BUFFER_FULL_ACTION>";
			xmlText += "<MULTIUSER>";
			xmlText += "<NAME></NAME>";
			xmlText += "<ALLOWREMOTESAVING>true</ALLOWREMOTESAVING>";
			xmlText += "<ALWAYSLISTENATSTARTUP>true</ALWAYSLISTENATSTARTUP>";
			xmlText += "<SHOW_CONNECTED_PORT_NAMES>true</SHOW_CONNECTED_PORT_NAMES>";
			xmlText += "<MU_PEERS>";
			xmlText += "<PEER>localhost:38000</PEER>";
			xmlText += "</MU_PEERS>";
			xmlText += "<REMOTE_SAVING_DEPTH>5</REMOTE_SAVING_DEPTH>";
			xmlText += "<MU_PASSWORD>cisco</MU_PASSWORD>";
			xmlText += "<MU_ACCEPT_MODE>2</MU_ACCEPT_MODE>";
			xmlText += "</MULTIUSER>";
			xmlText += "<IPC_MANAGER>";
			xmlText += "<METAFILE_PATH>../extensions/upnp/upnp.pta</METAFILE_PATH>";
			xmlText += "</IPC_MANAGER>";
			xmlText += "<IPC_ALLOWREMOTEAPPS>false</IPC_ALLOWREMOTEAPPS>";
			xmlText += "<RECENT_FILES/>";
			xmlText += "</OPTIONS>";
			xmlText += "<PHYSICALWORKSPACE>";
			xmlText += "<HOMERACK translate='true' >Intercity,Home City,Corporate Office,Main Wiring Closet</HOMERACK>";
			xmlText += "<NODE>";
			xmlText += "<X>0</X>";
			xmlText += "<Y>0</Y>";
			xmlText += "<TYPE>0</TYPE>";
			xmlText += "<NAME translate='true' >Intercity</NAME>";
			xmlText += "<SX>8.98473</SX>";
			xmlText += "<SY>14.4718</SY>";
			xmlText += "<W>20000</W>";
			xmlText += "<H>20000</H>";
			xmlText += "<PATH>../art/Background/gGeoViewInterCity.png</PATH>";
			xmlText += "<CHILDREN>";
			xmlText += "<NODE>";
			xmlText += "<X>200</X>";
			xmlText += "<Y>200</Y>";
			xmlText += "<TYPE>1</TYPE>";
			xmlText += "<NAME translate='true' >Home City</NAME>";
			xmlText += "<SX>1.18694</SX>";
			xmlText += "<SY>1.91755</SY>";
			xmlText += "<W>2000</W>";
			xmlText += "<H>2000</H>";
			xmlText += "<PATH>../art/Background/gGeoViewCity.png</PATH>";
			xmlText += "<CHILDREN>";
			xmlText += "<NODE>";
			xmlText += "<X>100</X>";
			xmlText += "<Y>100</Y>";
			xmlText += "<TYPE>2</TYPE>";
			xmlText += "<NAME translate='true' >Corporate Office</NAME>";
			xmlText += "<SX>0.174216</SX>";
			xmlText += "<SY>0.278164</SY>";
			xmlText += "<W>200</W>";
			xmlText += "<H>200</H>";
			xmlText += "<PATH>../art/Background/gGeoViewBuilding.png</PATH>";
			xmlText += "<CHILDREN>";
			xmlText += "<NODE>";
			xmlText += "<X>50</X>";
			xmlText += "<Y>50</Y>";
			xmlText += "<TYPE>3</TYPE>";
			xmlText += "<NAME translate='true' >Main Wiring Closet</NAME>";
			xmlText += "<SX>1</SX>";
			xmlText += "<SY>1</SY>";
			xmlText += "<W>20</W>";
			xmlText += "<H>20</H>";
			xmlText += "<PATH></PATH>";
			xmlText += "<CHILDREN>";
			xmlText += "<NODE>";
			xmlText += "<X>0</X>";
			xmlText += "<Y>0</Y>";
			xmlText += "<TYPE>4</TYPE>";
			xmlText += "<NAME translate='true' >Rack</NAME>";
			xmlText += "<SX>1</SX>";
			xmlText += "<SY>1</SY>";
			xmlText += "<W>0</W>";
			xmlText += "<H>0</H>";
			xmlText += "<PATH></PATH>";
			xmlText += "<CHILDREN>";

			foreach (NetworkNode node in nodes)
            {
				// ROUTER
				xmlText += "<NODE>";
				xmlText += "<X>" + node.Router.X + "</X>";
				xmlText += "<Y>" + node.Router.Y + "</Y>";
				xmlText += "<TYPE>6</TYPE>";
				xmlText += "<NAME translate='true' >" + node.Router.Name + "</NAME>";
				xmlText += "<SX>1</SX>";
				xmlText += "<SY>1</SY>";
				xmlText += "<W>0</W>";
				xmlText += "<H>0</H>";
				xmlText += "<PATH></PATH>";
				xmlText += "<CHILDREN/>";
				xmlText += "</NODE>";

				//SWITCH 1
				xmlText += "<NODE>";
				xmlText += "<X>" + node.Switch1.X + "</X>";
				xmlText += "<Y>" + node.Switch1.Y + "</Y>";
				xmlText += "<TYPE>6</TYPE>";
				xmlText += "<NAME translate='true' >" + node.Switch1.Name + "</NAME>";
				xmlText += "<SX>1</SX>";
				xmlText += "<SY>1</SY>";
				xmlText += "<W>0</W>";
				xmlText += "<H>0</H>";
				xmlText += "<PATH></PATH>";
				xmlText += "<CHILDREN/>";
				xmlText += "</NODE>";

				//SWITCH 2
				xmlText += "<NODE>";
				xmlText += "<X>" + node.Switch2.X + "</X>";
				xmlText += "<Y>" + node.Switch2.Y + "</Y>";
				xmlText += "<TYPE>6</TYPE>";
				xmlText += "<NAME translate='true' >" + node.Switch2.Name + "</NAME>";
				xmlText += "<SX>1</SX>";
				xmlText += "<SY>1</SY>";
				xmlText += "<W>0</W>";
				xmlText += "<H>0</H>";
				xmlText += "<PATH></PATH>";
				xmlText += "<CHILDREN/>";
				xmlText += "</NODE>";
			}

			xmlText += "</CHILDREN>";
			xmlText += "</NODE>";
			xmlText += "</CHILDREN>";
			xmlText += "</NODE>";
			xmlText += "</CHILDREN>";
			xmlText += "</NODE>";
			xmlText += "</CHILDREN>";
			xmlText += "</NODE>";
			xmlText += "</CHILDREN>";
			xmlText += "</NODE>";
			xmlText += "<BGPATH></BGPATH>";
			xmlText += "<NOTES/>";
			xmlText += "</PHYSICALWORKSPACE>";
			xmlText += "<FILTERS DHCP='yes' RIP='yes' SSH='yes' CDP='yes' Telnet='yes' HTTP='yes' OSPF='yes' LACP='yes' TCP='yes' ICMP='yes' ARP='yes' DNS='yes' VTP='yes' ICMPv6='yes' PAgP='yes' UDP='yes' STP='yes' TFTP='yes' EIGRP='yes' DTP='yes' >";
			xmlText += "<ACL_FILTERS>";
			xmlText += "<ACL_FILTER>";
			xmlText += "<NAME>ACL Filter</NAME>";
			xmlText += "<STATEMENTS></STATEMENTS>";
			xmlText += "<ENABLED>yes</ENABLED>";
			xmlText += "</ACL_FILTER>";
			xmlText += "</ACL_FILTERS>";
			xmlText += "</FILTERS>";
			xmlText += "<CLUSTERS>";
			xmlText += "<ROOTCLUSTER>";
			xmlText += "<NAME translate='true' >Root</NAME>";
			xmlText += "<CLUSTERID>1-1</CLUSTERID>";
			xmlText += "</ROOTCLUSTER>";
			xmlText += "</CLUSTERS>";
			xmlText += "<LINES/>";
			xmlText += "<RECTANGLES/>";
			xmlText += "<ELLIPSES/>";
			xmlText += "<USER_PROFILE>";
			xmlText += "<NAME>Guest</NAME>";
			xmlText += "<EMAIL></EMAIL>";
			xmlText += "<ADDITIONAL_INFO></ADDITIONAL_INFO>";
			xmlText += "</USER_PROFILE>";
			xmlText += "<MULTIUSER>";
			xmlText += "<REMOTE_NETWORKS/>";
			xmlText += "<PORT_VISIBILITY/>";
			xmlText += "</MULTIUSER>";
			xmlText += "<CEPS/>";
			xmlText += "</PACKETTRACER5>";
			xmlText += "";

			return xmlText;
		}

		public static List<ZipItem> GeneratePkts(GeneratorInput inputModel)
		{
			string rootDirectoryXmls = Constants.RootFolderPath + inputModel.NetworkName + @"\Xmls\";
			string rootDirectoryPkts = Constants.RootFolderPath + inputModel.NetworkName + @"\Pkts\";

			Directory.CreateDirectory(rootDirectoryXmls);
			Directory.CreateDirectory(rootDirectoryPkts);


			string currentFileName;
			string currentXmlData;
			List<NetworkNode> nodes;
			List<ZipItem> result = new List<ZipItem>();
			for (int i=2; i<=Convert.ToInt32(inputModel.Routers[0].Quantity); i++)
            {
				currentFileName = "version_" + (i-1).ToString();
				nodes = new List<NetworkNode>();

				CoordinatesGenerator.SetNumberOfSwitches(i*2);
				for(int j=0;j<i;j++)
                {
					nodes.Add(new NetworkNode());
				}

				currentXmlData = GenerateXmlData(nodes);
				using (FileStream fs = File.Create(rootDirectoryXmls + currentFileName + ".xml"))
				{
					byte[] info = new UTF8Encoding(true).GetBytes(currentXmlData);
					fs.Write(info, 0, info.Length);
				}

				XmlConverter.ConvertXmlToPkt(rootDirectoryXmls + currentFileName + ".xml", rootDirectoryPkts + currentFileName + ".pkt");

				result.Add(new ZipItem
				(
					currentFileName + ".pkt",
					System.IO.File.OpenRead(rootDirectoryPkts + currentFileName + ".pkt")
				));

				IdsGenerator.ResetCorrelative();
				CoordinatesGenerator.ResetCorrelative();
				AddressesGenerator.ResetCorrelatives();
			}
			return result;
		}
	}
}
